// AUTO-GENERATED by scripts/generate-image-manifest.mjs — do not edit by hand.
// Maps a Day Pillar romanization key (e.g. "sinhae") to its image URL under public/.
// Regenerate after adding images:  npm run images

export const ILJU_IMAGES: Record<string, string> = {
  byeongjin: "images/byeongjin.png",
  byeongo: "images/byeongo.png",
  eulmyo: "images/eulmyo.jpg",
  eulsa: "images/eulsa.png",
  gapin: "images/gapin.jpg",
  gimi: "images/gimi.jpg",
  giyu: "images/giyu.jpg",
  gyechuk: "images/gyechuk.png",
  gyehae: "images/gyehae.png",
  gyeongsin: "images/gyeongsin.png",
  gyeongsul: "images/gyeongsul.png",
  imja: "images/imja.png",
  imsul: "images/imsul.png",
  jeongmi: "images/jeongmi.png",
  jeongsa: "images/jeongsa.jpg",
  muo: "images/muo.png",
  musin: "images/musin.png",
  sinhae: "images/sinhae.png",
  sinyu: "images/sinyu.png",
};
